README.md

Let Release Please update the version in the README.md.

docs: automatically update versions in readme on release

---

README.md
samples/snippets/src/main/java/com/example/spanner/cassandra/QuickStartSample.java

docs: Format README and table comment

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/AdapterClientWrapper.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/AdapterClientWrapperTest.java

feat: Implement response stitching

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java

feat: Add RLS header

---

README.md

docs: Add comment to automatically update dependencies in spanner docs

---

README.md

Docs: update supported versions in README

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java

feat: Add support for direct path

---

.github/workflows/ci.yaml
integration-tests/pom.xml
integration-tests/src/test/java/com/google/cloud/spanner/adapter/AbstractIT.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/BasicIT.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/CassandraContext.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/ColumnDefinition.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/DatabaseContext.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/SpannerContext.java
pom.xml

chore: Setup basic integration test

---

.github/workflows/ci.yaml
.github/workflows/daily-integration.yml
.github/workflows/integration-tests.yml

chore: Setup daily integration tests

---

integration-tests/pom.xml
integration-tests/src/test/java/com/google/cloud/spanner/adapter/BasicIT.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/BatchStatementIT.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/CassandraContext.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/DatabaseContext.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/SpannerContext.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/TableDefinition.java

chore: Add more integration tests

---

README.md

We should keep updating this list to keep it up to date.

docs: add unsupported features from apache/cassandra-java-driver

---

.github/workflows/ci.yaml

ci: allow running it tests from forked repo

---

integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/PreparedStatementIT.java

I will add more tests under this file once they are working as expected !

ci: add it tests for prepare statement

---

.github/workflows/ci.yaml
.kokoro/build.sh
pom.xml

chore: Fix lint issues

---

.github/workflows/ci.yaml

chore: Upgrade java version for lint

---

integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/CounterIT.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/SetCollectionIT.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/TimestampIT.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/CassandraContext.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/DatabaseContext.java

ci: add it tests for counter, timestamp and set data types

---

.github/workflows/daily-integration.yml
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java

chore: Setup daily integration tests against devel endpoint

---

integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/RandomCqlDataGenerator.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/RandomSessionQueryGenerator.java
integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/RandomSessionQueryGeneratorIT.java

ci: add it tests for random value generator

---

.github/workflows/daily-integration.yml

chore: Fix it workflow

---

integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/MapCollectionIT.java

This test suite follows similar pattern with `SetCollectionIT.java`.

ci: add it tests for map collection type

---

.github/workflows/daily-integration.yml
.github/workflows/integration-tests.yml

chore: Fix IT again!!

---

integration-tests/src/test/java/com/google/cloud/spanner/adapter/cql/CastIT.java

ci: add IT tests for cast functions

---

integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/SpannerContext.java

chore: Fix integration tests against devel endpoint

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java

Add a default user agent string with client name + version + gax version.

chore: fix user-agent string

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/DriverConnectionHandler.java

chore: change log levels for some logs to debug to avoid noise

---

integration-tests/pom.xml
integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/CassandraContext.java

chore: Fix Cassandra IT

---

google-cloud-spanner-cassandra/pom.xml
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/AdapterClientWrapper.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/DriverConnectionHandler.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/PreparePayloadResult.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/util/ErrorMessageUtils.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/AdapterClientWrapperTest.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/DriverConnectionHandlerTest.java

fix: attach appropriate stream_id for error response

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/AdapterOptions.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/SpannerCqlSessionBuilder.java

chore: Fix code issue

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Launcher.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/SpannerCqlSession.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/SpannerCqlSessionBuilder.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/AdapterTest.java

chore: Make Adapter an AbstractApiService

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/Adapter.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/SpannerCqlSession.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/SpannerCqlSessionBuilder.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/AdapterTest.java

Reverts googleapis/java-spanner-cassandra#170

chore: Revert "Make Adapter an AbstractApiService"

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/AdapterClientWrapper.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/DriverConnectionHandler.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/PreparePayloadResult.java
google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/util/ErrorMessageUtils.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/AdapterClientWrapperTest.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/DriverConnectionHandlerTest.java

perf: Memory optimizations

---

google-cloud-spanner-cassandra/src/main/java/com/google/cloud/spanner/adapter/SpannerCqlRetryPolicy.java
google-cloud-spanner-cassandra/src/test/java/com/google/cloud/spanner/adapter/SpannerCqlRetryPolicyTest.java

fix: fix lint

---

integration-tests/src/test/java/com/google/cloud/spanner/adapter/utils/SpannerContext.java

chore: Increase control connection timeout in IT

---

README.md

chore: Remove "public preview"
